language: python
python: "2.7"

services:
  - docker

install:
  - export DOCKER_HUB_USERNAME="hutchic"
  - openssl aes-256-cbc -K $encrypted_9ca81b5594f5_key -iv $encrypted_9ca81b5594f5_iv -in id_rsa.enc -out id_rsa -d
  - eval `ssh-agent -s`
  - chmod 500 id_rsa
  - ssh-add id_rsa
  - git config --global user.name "Travis CI"
  - git config --global user.email office@mashape.com
  - git config --global push.default matching
  - docker pull mashape/semver
  - docker pull mashape/packerbuilder
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

script:
  - make create_ami
